[book]
authors = ["Petru Vamanu"]
language = "ro"
src = "src"
title = "Laborator ACSO"

[output.html]

[preprocessor.katex]
render-options.displayMode = true
render-options.fleqn = true
render-options.throwOnError = false